Fix/xml canonicalization failing on invalid namespace
SmartsquareGmbH/squit pull request #20
Opened 2021-02-24 13:06 UTC by KarstenSQ

2021-02-25 09:09 UTC, rubengees requested changes
Good work :+1:

I added some comments. Please also add the new property to the README with a short description what this does (the best place is the "Squit Dsl" section with a comment I think).

2021-02-25 09:09 UTC, rubengees commented on gradle/versions.gradle
> +    squitVersion = '3.0.3'
Please do not update the version number since this is tied to a README update and a release.

2021-02-25 09:09 UTC, rubengees commented on src/test/kotlin/de/smartsquare/squit/mediatype/xml/XmlCanonicalizerSpek.kt
> +                )
Nitpick: Style:

```suggestion
                val result = canonicalizer.canonicalize(
                    structure, MediaTypeConfig(
                        xmlStrict = false,
                        xmlCanonicalize = true,
                        jsonCanonicalize = false,
                        resolveInvalidNamespaces = true
                    )
                )
```

2021-02-25 09:09 UTC, rubengees commented on src/test/kotlin/de/smartsquare/squit/mediatype/xml/XmlCanonicalizerSpek.kt
> +                    <hello b="b">Abc</hello>
Let's add an "a" property here after the "b" to check that canonicalization works after resolving the namespace (see the "canonicalizing an xml structure -> should produce a valid result" spec).

2021-02-25 09:09 UTC, rubengees commented on src/main/kotlin/de/smartsquare/squit/mediatype/xml/XmlCanonicalizer.kt
> +        val regexNamespaces = Regex("xmlns([^\\s!>]+)")
Please move the regexes to `private val` in a new `private companion object` to avoid compiling them each time this function is run.

2021-02-26 13:31 UTC, KarstenSQ commented on src/main/kotlin/de/smartsquare/squit/SquitExtension.kt
> +        var resolveNamespaceString = "http://"
True, set to http://

2021-02-26 13:49 UTC, rubengees commented on src/main/kotlin/de/smartsquare/squit/SquitExtension.kt
> +        var resolveNamespaceString = "http://"
This input can be removed then, right?

2021-02-26 14:06 UTC, rubengees approved these changes

2021-02-26 14:06 UTC, merged